local util = require("util")

local root = util.root

-- Snacks picker keymaps (snacks itself is set up in bundles/ui; source
-- options for files/grep/explorer live there too). Keymaps only run at
-- keypress, so bundle load order doesn't matter.
vim.keymap.set("n", "<leader><space>", function()
  Snacks.picker.smart()
end, { desc = "Smart Find Files" })
vim.keymap.set("n", "<leader>/", function()
  Snacks.picker.grep({ cwd = root() })
end, { desc = "Grep (root dir)" })
vim.keymap.set("n", "<leader>:", function()
  Snacks.picker.command_history()
end, { desc = "Command History" })
vim.keymap.set("n", "<leader>ff", function()
  Snacks.picker.files({ cwd = root() })
end, { desc = "Find Files (root dir)" })
vim.keymap.set("n", "<leader>fF", function()
  Snacks.picker.files()
end, { desc = "Find Files (cwd)" })
vim.keymap.set("n", "<leader>fg", function()
  Snacks.picker.grep({ cwd = root() })
end, { desc = "Grep (root dir)" })
vim.keymap.set("n", "<leader>fG", function()
  Snacks.picker.grep()
end, { desc = "Grep (cwd)" })
vim.keymap.set("n", "<leader>fb", function()
  Snacks.picker.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>fh", function()
  Snacks.picker.help()
end, { desc = "Help Pages" })
vim.keymap.set("n", "<leader>fx", function()
  Snacks.picker.diagnostics_buffer()
end, { desc = "Diagnostics (buffer)" })
vim.keymap.set("n", "<leader>fX", function()
  Snacks.picker.diagnostics()
end, { desc = "Diagnostics (workspace)" })
vim.keymap.set("n", "<leader>sk", function()
  Snacks.picker.keymaps()
end, { desc = "Keymaps" })
vim.keymap.set("n", "<leader>sr", function()
  Snacks.picker.resume()
end, { desc = "Resume Last Picker" })
vim.keymap.set("n", "<leader>su", function()
  Snacks.picker.undo()
end, { desc = "Undo History" })
